server:
  port: 9000
spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  cloud:
    gateway:
      routes:
        - id: system
          uri: localhost:9001
          predicates:
            - Path=/system/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka